config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/get_user' =>'user#get_user'
  root 'shared#home'
  resources :user_profiles do
    collection do
      get 'get_user_profile'
    end
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :user_profile
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  include Paperclip::Glue
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment :avatar, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    users_get_user_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
  def home
    
  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
before_filter layout: false
  def get_user
    @users = User.all
  end

end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  #before_action :authenticate_user!
  skip_before_filter :verify_authenticity_token  

  def new
    @user_profile = current_user.build_user_profile
  end
  
  def create
    @user_profile = current_user.create_user_profile(user_profile_params)
    if @user_profile.save
      redirect_to root_path, notice: "Profile created_successfully"
    else
      render :new, alert: @user_profile.errors.full_messages.join(",")
    end
  end

  def get_user_profile
    user = User.find(params[:id]) 
    data = user.email
    render json: {data: data, avatar: user.user_profile  ? user.user_profile.avatar(:medium) : UserProfile.last.avatar(:medium)}
  end

  private
  def user_profile_params
    params.require(:user_profile).permit(:first_name, :last_name, :city, :state, :phone_no, :gender, :about_me, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/user_helper.rb
module UserHelper
  def any_error(user_profile)
    if user_profile.errors.any?
    errors = []
      user_profile.errors.full_messages.each do |msg|
        errors << "<li>#{msg}</li>"
      end
    end
  end
end

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grepdemo1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <div id="main">

    <!-- begin header -->
    <header>
      </script>
      <div id="logo"><h1>PHOTO<a href="#">ART</a>WORK 2_reverse</h1></div>
      <nav>
        <ul class="sf-menu" id="nav">
          <li class="selected"><%= link_to "home", root_path%></li>
          <li><%= link_to "about me", new_user_profile_path%></li>
          <li><a href="#">my portfolio</a>
            <ul>
              <li><a href="portfolio_one.html">portfolio_one</a></li>
              <li><a href="portfolio_two.html">portfolio_two</a></li>
            </ul>
          </li>
          <li><%= link_to "blog", get_user_profile_user_profiles_path, class: "blog-class" %></li>
          <li><a href="contact.html">contact</a></li>
            <% unless user_signed_in? %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path%></li>
            <% else %>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            <% end%>
        </ul>
      </nav>
    </header>
  </div>
<body>
<%= yield %>
</body>
<div id="main">
  <footer>
    <p>Copyright &copy; 2012 PhotoArtWork2_reverse. All Rights Reserved. <a href="http://www.css3templates.co.uk">Design from css3templates.co.uk</a>.</p>
    <p><img src="<%= asset_path("twitter.png")%>" alt="twitter" />&nbsp;<img src="<%= asset_path("facebook.png")%>" alt="facebook" />&nbsp;<img src="<%= asset_path("rss.png")%>" alt="rss" /></p>
  </footer>
</div>
</html>

<script type="text/javascript">
  $(document).ready(function() {
      $('ul.sf-menu').sooperfish();
    });
</script>

app/views/shared/home.html.erb
<div id="site_content">
  <ul class="slideshow">
    <li class="show"><img width="950" height="450" src="<%= asset_path("home_1.jpg")%>" alt="&quot;You can put a caption for your image right here&quot;" /></li>
    <li><img width="950" height="450" src="<%= asset_path("home_2.jpg")%>" alt="&quot;You can put a description of the image here if you like, or anything else if you want.&quot;" /></li>
    <li><img width="950" height="450" src="<%= asset_path("home_2.jpg")%>" alt="&quot;You can put a description of the image here if you like, or anything else if you want.&quot;" /></li>
  </ul>
</div>
<div id="summernote-custom">
  
</div>

app/views/user/get_user.html.erb
<div id="site_content">
  <div id="left_content">
  <%@users.each do |user|%>
    <div id="blog_container">
      <div class="blog"><h2>May</h2><h3>20th</h3></div>
      <h4><a href="javascript:void(0);", class="user_profile", data-item="<%= user.id%>" ><%= user.email%></a></h4>
      <p>Your profile yet not completed please complete it first to serve all features. <a href="">read more.....</a></p>
    </div> 
  <% end %>
  </div>
  <div id="right_content">
    <div id="blog_text">
      <h1>Wedding Shoot in Edinburgh</h1>
      <img src="" alt="one", class="blog-image" /></br>
      <p id="blog-p"></p>
      <!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui.</p> -->
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $(".user_profile").on('click', function(){
      var id = $(this).attr('data-item');
      $.ajax({
        method: 'get',
        url: "/user_profiles/get_user_profile",
        data: {id: id}
      }).done(function(data) {
        $("#blog-p").text(data.data);
        $(".blog-image").attr('src', data.avatar);
      });
    });
  });
</script>

<script type="text/html">
  #right_content
  {
    background-image:url();
  }

</script>

app/views/user_profiles/new.html.erb
<div id="site_content">
  <div id="left_content">
    <h1>Join us here</h1>
    <%= form_for @user_profile, remote: true do |f|%>
      <div class="form_settings">
        <p><span>First name</span><%= f.text_field :first_name%></p>
        <p><span>Last name</span><%= f.text_field :last_name%></p>
        <p><span>Phone no</span><%= f.text_field :phone_no%></p>
        <p><span>Gender</span><%= f.text_field :gender%></p>
        <p><span>City</span><%= f.text_field :city%></p>
        <p><span>State</span><%= f.text_field :state%></p>
        <p><span>About me</span><%= f.text_area :about_me%></p>
        <p><span>Avatar</span><%= f.file_field :avatar, as: :image %></p>
        <p style="padding-top: 15px"><span>&nbsp;</span>
        <%=f.submit "Register", class: "submit"%>
        </p>
      </div>
    <% end%>
  </div>
</div>